### ISSUE TITLE
 joint_limits.yaml file and saftey configuration on ur5 control panel 

### ISSUE THREAD

**Issue by ShuSewts** [UniversalRobots/Universal_Robots_ROS_Driver#220]
I've been asked to post here, here's the original [question:](https://answers.ros.org/question/356557/joint_limitsyaml-file-and-saftey-configuration-on-ur5-control-panel-am/)

I am using ROS Kinetic, moveit, and a ur5 with a polyscope version of 3.1.0.0.76181. 
I have changed the safefty configuration on the ur5 control panel to limit the maximum joint speed to 80 degrees/second. This resulted in some stuttering when moving the robot with moveit and a very quick acceleration (the robot started to move almost immediately at a fast speed and decelerated very quickly near the end of its trajectory) so I changed the default values in the joint_limits.yaml file inside the ur5_moveit_config to match the joint speed limits on the control panel. As no acceleration values can be found on the control panel, I changed the acceleration on the joints to be the same as the velocity. The robot is now able to accelerate smoothly, but I am still getting some stuttering in trajectories. Can anyone point me in the right direction? Attached my joint_limits.yaml file for reference. 

```
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.2211
    has_acceleration_limits: true
    max_acceleration: 1.2211
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.2211
    has_acceleration_limits: true
    max_acceleration: 1.2211
  elbow_joint:
    has_velocity_limits: false
    max_velocity: 1.2211
    has_acceleration_limits: true
    max_acceleration: 1.2211
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 1.2211
    has_acceleration_limits: true
    max_acceleration: 1.2211
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 1.2211
    has_acceleration_limits: true
    max_acceleration: 1.2211
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 1.2211
    has_acceleration_limits: true
    max_acceleration: 1.2211
```
