### ISSUE TITLE
Jerky motion even when using vel_traj_controller of ur_robot_driver

### ISSUE THREAD

**Issue by blackhorsewu** [UniversalRobots/Universal_Robots_ROS_Driver#267]
*Introduction to the issue*

# Versions
 - ROS Driver version: ur_robot_driver
 - Affected Robot Software Version(s): URSoftware 3.10
 - Affected Robot Hardware Version(s):
 - Robot Serial Number: UR5
 - UR+ product(s) installed:
 - URCaps Software version(s):

# Issue details

When I was using `ur_modern_driver` on ur3 last year, the `ros vel_based_pos_traj_controller`, the manipulator can move smoothly. Now, I am trying the `vel_traj_controller` of the `ur_robot_driver` on ur5, the movement of the manipulator is very jerky!

I just noticed that `vel_traj_controller` is different from `vel_based_pos_traj_controller`. I suppose I should have used `vel_based_pos_traj_controller` if it ever exist! If it is not available yet, when would it be available at all?

Is there any thing that can be done to smooth the motion for the time being?

Thank you for your help.

**Comment by gavanderhoorn** [comment]
> Now, I am trying the `vel_traj_controller`

Please tell us where you find this controller defined.

I cannot find it in the files in [ur_robot_driver/config](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/406a3308d8d45906d83acd7fa4263cd6476223f3/ur_robot_driver/config).

**Comment by blackhorsewu** [comment]
In the `ur_robot_driver/config/ur5_controllers.yaml` file, there are `scaled_vel_traj_controller` and `vel_traj_controller sections`.

**Comment by gavanderhoorn** [comment]
Please link to specific line number in the file.

Afaict, that file contains these entries for velocity related controllers:

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/406a3308d8d45906d83acd7fa4263cd6476223f3/ur_robot_driver/config/ur5_controllers.yaml#L64-L131

**Comment by fmauch** [comment]
@blackhorsewu I suppose you did not pull the latest version as those got renamed in 7ac5b4d235cb3cfd95f1c2ebe052c776e2e3263a 2 months ago.

Furthermore, I am assuming you are referring to what we now call `vel_joint_traj_controller`.

**Comment by blackhorsewu** [comment]
@fmauch and @gavanderhoorn No, I did not pull the latest version. I was just checking the dates of the files. The last modified dates of my files are 6 June and the dates on the github files are 28 days ago. Anyway the contents of these sections are the same, as far as I can tell.

**Comment by blackhorsewu** [comment]
Actually, when I use the `vel_traj_controller` it is already better that `scaled_vel_traj_controller`.

**Comment by gavanderhoorn** [comment]
To avoid confusion: could you please copy-paste the contents of your `ur5_controllers.yaml` here in a comment (be sure to paste it into a [markdown code block](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)).

I find it very hard to reason about what you are doing, as you refer to names which are no longer used here.

**Comment by fmauch** [comment]
And as you can see in

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/406a3308d8d45906d83acd7fa4263cd6476223f3/ur_robot_driver/config/ur5_controllers.yaml#L109

the pid values for the controller aren't optimized in any way. 

If you like, you can try adapting those values to the ones from the ur_modern_driver

https://github.com/ros-industrial/ur_modern_driver/blob/kinetic-devel/config/ur5_controllers.yaml#L77-L83

If that helps, please let us know.

**Comment by blackhorsewu** [comment]
@gavanderhoorn , the following is the content of my `ur5_controllers.yaml`
```
# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: &loop_hz 125

# Settings for ros_control hardware interface
hardware_interface:
   joints: &robot_joints
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: *loop_hz

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: *loop_hz

# Publish speed_scaling factor
speed_scaling_state_controller:
   type:         ur_controllers/SpeedScalingStateController
   publish_rate: *loop_hz

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
scaled_pos_traj_controller:
   type: position_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      elbow_joint: {trajectory: 0.2, goal: 0.1}
      wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 10

pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      elbow_joint: {trajectory: 0.2, goal: 0.1}
      wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 10

scaled_vel_traj_controller:
   type: velocity_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  *loop_hz
   action_monitor_rate: 10
   gains:
      #!!These values have not been optimized!!
      shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}

   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      shoulder_pan_joint: 1.0
      shoulder_lift_joint: 1.0
      elbow_joint: 1.0
      wrist_1_joint: 1.0
      wrist_2_joint: 1.0
      wrist_3_joint: 1.0

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #stop_trajectory_duration: 0 # Defaults to 0.0

vel_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  *loop_hz
   action_monitor_rate: 10
   gains:
      #!!These values have not been optimized!!
      shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}

   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      shoulder_pan_joint: 1.0
      shoulder_lift_joint: 1.0
      elbow_joint: 1.0
      wrist_1_joint: 1.0
      wrist_2_joint: 1.0
      wrist_3_joint: 1.0

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #stop_trajectory_duration: 0 # Defaults to 0.0

# Pass an array of joint velocities directly to the joints
joint_group_vel_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints: *robot_joints

robot_status_controller:
   type: industrial_robot_status_controller/IndustrialRobotStatusController
   handle_name: industrial_robot_status_handle
   publish_rate: 10

controller_list:
  - name: ""
#    action_ns: joint_trajectory_action
    action_ns: scaled_vel_traj_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint] 
```
