### ISSUE TITLE
UR5 CB3 not moving when using /scaled_pos_joint_traj_controller action

### ISSUE THREAD

**Issue by FrederikPlahl** [UniversalRobots/Universal_Robots_ROS_Driver#305]
# Summary
My UR5 CB3 is not moving but accepting the goals and setting them to active and also giving feedback when using the /scaled_pos_joint_traj_controller/follow_joint_trajectory action.

*Introduction to the issue*
I'm using the /scaled_pos_joint_traj_controller/follow_joint_trajectory action and sending 3 waypoints via a client I have written. Basically the shoulder_pan_joint should turn 90° and turn back into home position.
When sending the goal to the action I can see the /scaled_pos_joint_traj_controller/follow_joint_trajectory/feedback topic giving me the desired, actual and error positions. These positions are basically all the same (error is about 2,5 e-05) so I'd expect the robot to go to the next waypoint but it isn't. I also have goal tolerances for every joint of 0.1 so it should accept the goal.

I have no idea why it is not moving because also no error is posted anywhere.
PS: Speed slider is at 100% and program isn't paused.

**/scaled_pos_joint_traj_controller/follow_joint_trajectory/goal topic**

```
neobotix@mmo-500-1:~$ rostopic echo /scaled_pos_joint_traj_controller/follow_joint_trajectory/goal 
header: 
  seq: 0
  stamp: 
    secs: 1609853735
    nsecs: 760345310
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1609853735
    nsecs: 760345861
  id: "/follow_joint_client-1-1609853735.760345861"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1609853737
        nsecs: 760325830
      frame_id: ''
    joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint,
  wrist_3_joint]
    points: 
      - 
        positions: [0.0, -1.5707963267948966, 0.0, -1.5707963267948966, 0.0, 0.0]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [1.5707963267948966, -1.5707963267948966, 0.0, -1.5707963267948966, 0.0, 0.0]
        velocities: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        accelerations: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        effort: []
        time_from_start: 
          secs: 4
          nsecs:         0
      - 
        positions: [0.0, -1.5707963267948966, 0.0, -1.5707963267948966, 0.0, 0.0]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        effort: []
        time_from_start: 
          secs: 7
          nsecs:         0
  path_tolerance: []
  goal_tolerance: 
    - 
      name: "shoulder_pan_joint"
      position: 0.1
      velocity: 0.1
      acceleration: 0.1
    - 
      name: "shoulder_lift_joint"
      position: 0.1
      velocity: 0.1
      acceleration: 0.1
    - 
      name: "elbow_joint"
      position: 0.1
      velocity: 0.1
      acceleration: 0.1
    - 
      name: "wrist_1_joint"
      position: 0.1
      velocity: 0.1
      acceleration: 0.1
    - 
      name: "wrist_2_joint"
      position: 0.1
      velocity: 0.1
      acceleration: 0.1
    - 
      name: "wrist_3_joint"
      position: 0.1
      velocity: 0.1
      acceleration: 0.1
  goal_time_tolerance: 
    secs: 2
    nsecs:         0
---
```

**/scaled_pos_joint_traj_controller/follow_joint_trajectory/feedback topic**

```
neobotix@mmo-500-1:~$ rostopic echo /scaled_pos_joint_traj_controller/follow_joint_trajectory/feedback
header: 
  seq: 58
  stamp: 
    secs: 1609854642
    nsecs: 418980184
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1609854639
      nsecs: 249994710
    id: "/follow_joint_client-1-1609854639.249994710"
  status: 1
  text: ''
feedback: 
  header: 
    seq: 0
    stamp: 
      secs: 1609854642
      nsecs: 413816973
    frame_id: ''
  joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint,
  wrist_3_joint]
  desired: 
    positions: [-1.1746083394825746e-05, -1.5707357565509241, 6.008148193359375e-05, -1.5707724730121058, 1.1984225238848012e-05, -4.7985707418263246e-05]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: []
    time_from_start: 
      secs: 0
      nsecs:         0
  actual: 
    positions: [1.1984225238848012e-05, -1.570808235798971, 8.392333984375e-05, -1.5707481543170374, -4.7985707418263246e-05, -3.5587941304981996e-05]
    velocities: [0.0, 0.0, -0.0, 0.0, 0.0, 0.0]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 0
      nsecs:         0
  error: 
    positions: [-2.3730308633673758e-05, 7.2479248046875e-05, -2.384185791015625e-05, -2.4318695068359375e-05, 5.996993265711126e-05, -1.239776611328125e-05]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 0
      nsecs:         0
---
```
## My code

```c++
#include <ros/ros.h>
#include <trajectory_msgs/JointTrajectory.h>
#include <trajectory_msgs/JointTrajectoryPoint.h>
#include <control_msgs/FollowJointTrajectoryAction.h>
#include <control_msgs/FollowJointTrajectoryGoal.h>
#include <actionlib/client/simple_action_client.h>
#define _USE_MATH_DEFINES
#include <cmath>

typedef actionlib::SimpleActionClient<control_msgs::FollowJointTrajectoryAction> Client;

int main(int argc, char** argv){
  ros::init(argc, argv, "follow_joint_client");
  Client * client;
  client = new Client("/scaled_pos_joint_traj_controller/follow_joint_trajectory", true);
  ROS_INFO("Waiting for action server to start.");
  client->waitForServer();
  
  ROS_INFO("Action server started, sending goal.");
  control_msgs::FollowJointTrajectoryGoal goal;
  //Filling goal:
  trajectory_msgs::JointTrajectory trajectory;
  trajectory_msgs::JointTrajectoryPoint points;
  control_msgs::JointTolerance path_tolerance;
  control_msgs::JointTolerance goal_tolerance;
  ros::Duration goal_time_tolerance;

  //trajectory header
  goal.trajectory.header.stamp = ros::Time::now()+ros::Duration(2); 

  //joint_names
  goal.trajectory.joint_names.resize(6);
  
  goal.trajectory.joint_names[0] = "shoulder_pan_joint";
  goal.trajectory.joint_names[1] = "shoulder_lift_joint";
  goal.trajectory.joint_names[2] = "elbow_joint";
  goal.trajectory.joint_names[3] = "wrist_1_joint";
  goal.trajectory.joint_names[4] = "wrist_2_joint";
  goal.trajectory.joint_names[5] = "wrist_3_joint";
  
  //first trajectory point:
  //positions
  int ind = 0;
  goal.trajectory.points.resize(3);
  goal.trajectory.points[ind].positions.resize(6);
  
  goal.trajectory.points[ind].positions[0] = 0;
  goal.trajectory.points[ind].positions[1] = -M_PI_2;
  goal.trajectory.points[ind].positions[2] = 0;
  goal.trajectory.points[ind].positions[3] = -M_PI_2;
  goal.trajectory.points[ind].positions[4] = 0;
  goal.trajectory.points[ind].positions[5] = 0;
  
  //velocities
  goal.trajectory.points[ind].velocities.resize(6);
  for (size_t j = 0; j < 6; ++j)
  {
    goal.trajectory.points[ind].velocities[j] = 0.0;
  }
  //accelerations
  goal.trajectory.points[ind].accelerations.resize(6);
  for (size_t j = 0; j < 6; ++j)
  {
    goal.trajectory.points[ind].accelerations[j] = 0.0;
  }

  // To be reached at start
  goal.trajectory.points[ind].time_from_start = ros::Duration(0.0);
  
  //second trajectory point:
  //postitions
  ind += 1;
  goal.trajectory.points[ind].positions.resize(6);
  
  goal.trajectory.points[ind].positions[0] = M_PI_2;
  goal.trajectory.points[ind].positions[1] = -M_PI_2;
  goal.trajectory.points[ind].positions[2] = 0;
  goal.trajectory.points[ind].positions[3] = -M_PI_2;
  goal.trajectory.points[ind].positions[4] = 0;
  goal.trajectory.points[ind].positions[5] = 0;
  
  //velocities
  goal.trajectory.points[ind].velocities.resize(6);
  for (size_t j = 0; j < 6; ++j)
  {
    goal.trajectory.points[ind].velocities[j] = 1.0;
  }
  //accelerations
  goal.trajectory.points[ind].accelerations.resize(6);
  for (size_t j = 0; j < 6; ++j)
  {
    goal.trajectory.points[ind].accelerations[j] = 1.0;
  }

  // To be reached 4 seconds after starting along the trajectory
  goal.trajectory.points[ind].time_from_start = ros::Duration(4.0);

  //third trajectory point:
  //postitions
  ind += 1;
  goal.trajectory.points[ind].positions.resize(6);
  
  goal.trajectory.points[ind].positions[0] = 0;
  goal.trajectory.points[ind].positions[1] = -M_PI_2;
  goal.trajectory.points[ind].positions[2] = 0;
  goal.trajectory.points[ind].positions[3] = -M_PI_2;
  goal.trajectory.points[ind].positions[4] = 0;
  goal.trajectory.points[ind].positions[5] = 0;
  
  //velocities
  goal.trajectory.points[ind].velocities.resize(6);
  for (size_t j = 0; j < 6; ++j)
  {
    goal.trajectory.points[ind].velocities[j] = 0.0;
  }
  //accelerations
  goal.trajectory.points[ind].accelerations.resize(6);
  for (size_t j = 0; j < 6; ++j)
  {
    goal.trajectory.points[ind].accelerations[j] = 1.0;
  }

  // To be reached 7 seconds after starting along the trajectory
  goal.trajectory.points[ind].time_from_start = ros::Duration(7.0);

//goal tolerances:
  goal.goal_tolerance.resize(6);
  
  goal.goal_tolerance[0].name = "shoulder_pan_joint";
  goal.goal_tolerance[0].position = 0.1;
  goal.goal_tolerance[0].velocity = 0.1;
  goal.goal_tolerance[0].acceleration = 0.1;
  
  goal.goal_tolerance[1].name = "shoulder_lift_joint";
  goal.goal_tolerance[1].position = 0.1;
  goal.goal_tolerance[1].velocity = 0.1;
  goal.goal_tolerance[1].acceleration = 0.1;
  
  goal.goal_tolerance[2].name = "elbow_joint";
  goal.goal_tolerance[2].position = 0.1;
  goal.goal_tolerance[2].velocity = 0.1;
  goal.goal_tolerance[2].acceleration = 0.1;
  
  goal.goal_tolerance[3].name = "wrist_1_joint";
  goal.goal_tolerance[3].position = 0.1;
  goal.goal_tolerance[3].velocity = 0.1;
  goal.goal_tolerance[3].acceleration = 0.1;

  goal.goal_tolerance[4].name = "wrist_2_joint";
  goal.goal_tolerance[4].position = 0.1;
  goal.goal_tolerance[4].velocity = 0.1;
  goal.goal_tolerance[4].acceleration = 0.1;

  goal.goal_tolerance[5].name = "wrist_3_joint";
  goal.goal_tolerance[5].position = 0.1;
  goal.goal_tolerance[5].velocity = 0.1;
  goal.goal_tolerance[5].acceleration = 0.1;

  goal.goal_time_tolerance = ros::Duration(2.0);

  //sending goal:
  client->sendGoal(goal);

  //result:
 
  while (client->getState() != actionlib::SimpleClientGoalState::SUCCEEDED && ros::ok()){
    client->waitForResult(ros::Duration(1)); 
    
    printf("Current State: %s\n", client->getState().toString().c_str());
    sleep(2);
  }
  printf("Action ended!\n");
  return 0;
};
```

Thanks a lot in advance for helping!
