### ISSUE TITLE
Weird DH parameters reading from ur_calibration

### ISSUE THREAD

**Issue by thachdo** [UniversalRobots/Universal_Robots_ROS_Driver#457]
I'm using UR5 with ROS Kinetic. The result of reading calibrated parameters using [ur_calibration](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/master/ur_calibration) is as follows:

```
dh_theta: [-9.62699668632896e-06 -1.43707039992005 2.02543119975016 -0.588254688694989 4.13647390228702e-05 8.1737464953645e-06 ]

dh_a: [0.000279332356195598 -0.0566854832098269 -0.32646702272051 1.49388687216263e-05 2.23692592990586e-07 0 ]

dh_d: [0.0888794492754001 574.241384579456 -507.363402098168 -66.7676839353205 0.0949734691141216 0.0825625014554953 ]

dh_alpha: [1.57033858830411 -0.000733893428160216 0.00325607356326439 1.57040005185553 -1.57101000328584 0 ]
```
which is quite different from standard parameters [here](https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/). Specifically,
dh_a[1] is too small and dh_d[1:4] are too large. Is this abnormal? How could I resolve that issue?

The result of the .yaml file is:
```
kinematics:
  hash: calib_11914550710326326731
  shoulder:
    x: 0
    y: 0
    z: 0.08887944927540013
    roll: -0
    pitch: 0
    yaw: -9.626996686328957e-06
  upper_arm:
    x: 0.0002793323561955981
    y: 0
    z: 0
    roll: 1.570338588304109
    pitch: 0
    yaw: 2.158839766170508e-05
  forearm:
    x: -0.4252272570400704
    y: 0
    z: 0
    roll: 3.141494820936201
    pitch: 3.140865310247571
    yaw: -3.141502430632191
  wrist_1:
    x: -0.3922288019679848
    y: -0.0003001522770219462
    z: 0.1108071247640628
    roll: 0.002708774761028905
    pitch: 0.001806809986672728
    yaw: -8.11176398879282e-06
  wrist_2:
    x: 1.493886872162628e-05
    y: -0.09497346165709802
    z: 3.763560472995243e-05
    roll: 1.570400051855527
    pitch: 0
    yaw: 4.136473902287017e-05
  wrist_3:
    x: 2.236925929905856e-07
    y: 0.08256249957069076
    z: -1.764166546013033e-05
    roll: 1.570582650303955
    pitch: 3.141592653589793
    yaw: -3.141584479843298
```
which is more close to the standard values. My target is to get the calibrated DH parameters. Is there any script to convert the .yaml file to DH parameters? Also, can I read the DH params directly from the teaching pendant interface?
