### ISSUE TITLE
Can't simultaneously control multiple robots

### ISSUE THREAD

**Issue by xiaohuits** [UniversalRobots/Universal_Robots_ROS_Driver#81]
Hi, I am testing this driver with a dual-arm UR5e setup in our lab. I can correctly start the driver for one arm at a time but couldn't find a way to control the two arms at the same time (using a single computer). 

I have two launch files (`left_arm_bringup.launch` and `right_arm_bringup.launch`) that can correctly start the driver for the left/right arm. These launch files are just copies of `ur5e_bringup.launch` with IP and calibration file provided. 

Here is what I have tried to launch driver for both arms at the same time:
```
file: both_arm_bringup.launch
<?xml version="1.0"?>
<launch>
  <include file="$(find macs_ur_launch)/launch/left_arm_bringup.launch" ns="left_arm"/>
  <include file="$(find macs_ur_launch)/launch/right_arm_bringup.launch" ns="right_arm"/>
</launch>
```
I wanted to prefix the services/topics with different namespaces for each arm, so the message sent will not conflict. However, it seems that this is not going to work. It will produce a runtime error says "Connection setup failed for :50002". See the log here: [log.txt](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/files/4075170/log.txt)

It seems that the underlying connections can't be launched multiple times? Is there any other way that I can built the connections for both robots at the same time?

**Comment by fmauch** [comment]
First of all: I don't think, it is a very good idea to control two arms from one machine, as they will share resources (computation wise and (depending on your network setup) communication wise).

However, if you want to go ahead and do this, you'll have to adapt the reverse_port 50001 and the script_sender_port 50002 for one of the drivers (They are launch file parameters).

See #57 where this got implemented.

Please try this out and let us know whether this works in your situation.

**Comment by xiaohuits** [comment]
Thanks for the quick comments! The two arms will collaborate together for a common task so it will be nature for me to putting everything in the same machine first and plan together. Thanks for the head-up information through. 

I changed the reverse_port and script_sender_port of the second arm to a different number and now the both drivers can start without error.  

However, the ```rqt_joint_trajectory_controller``` will fail when I choose one of the controller manager namespace. Not sure if the driver is working correctly or not, or this is an issue with the rqt tool. I can use the rqt tool when only one driver is running.

> Error message from rqt_joint_trajectory_controller
> Traceback (most recent call last):
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_joint_trajectory_controller/joint_trajectory_controller.py", line 271, in _on_cm_change
>     self._update_jtc_list()
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_joint_trajectory_controller/joint_trajectory_controller.py", line 243, in _update_jtc_list
>     self._robot_joint_limits = get_joint_limits()  # Lazy evaluation
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_joint_trajectory_controller/joint_limits_urdf.py", line 21, in get_joint_limits
>     description = rospy.get_param(key)
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 465, in get_param
>     return _param_server[param_name] #MasterProxy does all the magic for us
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msproxy.py", line 123, in __getitem__
>     raise KeyError(key)
> KeyError: 'robot_description'

I am trying to use MoveIt! interface to test out. Will update when I have more information.

**Comment by fmauch** [comment]
Running everything in a namespace is quire important, as well. See the discussion in #45.

**Comment by felixvd** [comment]
I am having issues with this as well. With `ur_modern_driver`, we used to have two UR robots prefixed with a unique name, by specifying a `prefix` parameter in the launch file spawning the driver node and in the URDF file calling the UR macro, so that both driver nodes publish in the root namespace and connect to the same `move_group`. However, in `ur_robot_driver`, the `tf_prefix` parameter handed into `ur_control.launch` does not seem to affect the joint names that are published to `/joint_states` - they are published without any prefix (e.g. `shoulder_pan_joint` instead of `b_bot_shoulder_pan_joint`).

Is this by design? How are multiple robots meant to be controlled together? Do we need to put them in different namespaces and create two entirely separate move_groups now? Maintaining the same `PlanningScene` seems error-prone and like a hassle.

I would appreciate any comments you have, also regarding how `roscontrol` would work with multiple robots, as I have not used it much. You can see the `moveit_config` we had in our system [here](https://github.com/o2as/ur-o2as/tree/master/catkin_ws/src/o2as_moveit_config).

**Comment by gavanderhoorn** [comment]
`tf_prefix` is indeed only used to prefix the TF frames published by the driver ([here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/a926789adc0cefc616beb0fda15793cdcd65831b/ur_robot_driver/src/ros/hardware_interface.cpp#L111-L112)).

There is no prefix for the joint names specifically, as you're supposed to tell the `hardware_interface` which joints you'd like it to expose. The default joint names are defined in the `.yaml` files in the [config](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/c9b25b5a790a9efd6492a42f1706aeadb0803ca9/ur_robot_driver/config) directory or `ur_robot_driver`. For the UR5 fi:

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/c9b25b5a790a9efd6492a42f1706aeadb0803ca9/ur_robot_driver/config/ur5_controllers.yaml#L6-L13

This list of joints is then used everywhere (note the anchor (`&robot_joints`), it's used later in the file to refer back to this list, using an alias (`*`)).

The `ros_control` `JointStateController` is then responsible for publishing `JointState` messages using information coming from the `hardware_interface` (it's not really a controller, but that's `ros_control` nomenclature). `JointStateController` publishes for *all* joints registered in a `hardware_interface`.

The `ur_robot_driver` `hardware_interface` only registers the names specified in the `hardware_interface` sub section of the config `.yaml` (shown above).

Taking these two things together: you don't really "prefix joint names" in so much as you specify completely new ones (the fact that it's a prefix is only apparent to you, a human). The `hardware_interface` will then register those names as names for the joints (internally it really only uses indices into arrays, names are for humans :man_shrugging:) and the `JointStateController` will start publishing `JointState` messages for all those joints *in that specific `hardware_interface`*.

So for a multi-robot setup, start two instances of the driver (each in their own namespace), make sure to create two copies of the configuration `.yaml` (one for each of the driver instances), load them in their respective namespaces and make sure to specify the correct joint names for each.

You should end up with two `ur_robot_driver` instances each publishing to a `joint_states` topic in their own namespace, which you could then combine into a single publication on `/joint_states` (or whichever topic you prefer) by running `joint_state_publisher` with a `source_list` parameter correctly configured.

---

PS: you appear to have an entire Catkin workspace in a git repository. Not very elegant .. ;)

**Comment by xiaohuits** [comment]
Update: Thanks everyone! I can simultaneously run two drivers to control two UR5e robots with moveit now. Here are the summary of the tricks applied:
- Each robot will need to have different reverse_port and the script_sender_port value. 
- Use a namespace for each group of launch files that are used for launch the driver, moveit package and rviz for a single robot.

Details of my launch files can be found [here](https://github.com/macs-lab/macs_dual_arm)

**Comment by felixvd** [comment]
Thanks for the detailed response! I will make separate versions of `ur5_controllers.yaml` with the joint names changed to include the prefix. I am not sure of some points:

- if they will need to be in their own namespace or changing the `ur_robot_driver` node's name will suffice
- in case they do need their own namespace, which other nodes from `ur_common.launch` need to be in it (e.g. `ur_robot_state_helper`, `controller_manager`, `ur_tool_communication_bridge`)
- which of those nodes could be shared between the `ur_robot_driver` nodes
- how to configure the `source_list` parameter of the `joint_state_publisher`. I would have simply tried to remap the `/joint_states` topic from the driver's namespace to the global one.

I am mostly noting this for documentation. I assume I would know if I was more familiar with the way `roscontrol`'s `controller_manager` works. I will update when I get to it. 

> PS: you appear to have an entire Catkin workspace in a git repository. Not very elegant .. ;)

Actually it's even more: a catkin workspace, the environment Dockerfile and the scripts to install and run it locally. It's a little custom, but fully documented in the wiki, and from experience it helps onboard new users and streamline their installs immensely.

**Comment by gavanderhoorn** [comment]
> Thanks for the detailed response! I will make separate versions of `ur5_controllers.yaml` with the joint names changed to include the prefix. I am not sure of some points:
> 
> * if they will need to be in their own namespace or changing the `ur_robot_driver` node's name will suffice

both driver instances need their own namespace.

Reason is that it all comes down to parameters, and those are looked up in the namespace the driver node is in. As there's no way to have multiple sets of parameters in the same namespace with the same name, you'll need namespaces.

> * in case they do need their own namespace, which other nodes from `ur_common.launch` need to be in it (e.g. `ur_robot_state_helper`, `controller_manager`, `ur_tool_communication_bridge`)

All of them.

As @xiaohuits wrote: just namespace the launch files. The rest should work automatically.

> * which of those nodes could be shared between the `ur_robot_driver` nodes

None (or at least: I would not do that if you're just starting out).

> * how to configure the `source_list` parameter of the `joint_state_publisher`. I would have simply tried to remap the `/joint_states` topic from the driver's namespace to the global one.

Remapping can work, but that will mean that `/joint_states` consumers will receive "incomplete" `JointState` messages (ie: first of robot1, then robot2, etc).

If you use the JSP with `source_list` set to something like `['/ns_of_robot1/joint_states', '/ns_of_robot2/joint_states']` it will coalesce those into a single message and publish it on `/joint_states`. Subscribers to that topic will see a single message describing the whole system, which is much more robust.

> I am mostly noting this for documentation. I assume I would know if I was more familiar with the way `roscontrol`'s `controller_manager` works. I will update when I get to it.

I don't believe this is very tightly coupled to `ros_control` actually: it's just nodes which expect certain parameters to exist (buth with different values) and you want two sets of those parameters to exist. The typical pattern to follow is to place such nodes and their parameters in a namespace.

As to the joint names: I guess that could be called `ros_control` behaviour but in reality I've always thought the `prefix` parameter was a bit hacky. It's much cleaner to isolate things properly, and the way to do that is again namespaces.

> > PS: you appear to have an entire Catkin workspace in a git repository. Not very elegant .. ;)
> 
> Actually it's even more: a catkin workspace, the environment Dockerfile and the scripts to install and run it locally. It's a little custom, but fully documented in the wiki, and from experience it helps onboard new users and streamline their installs immensely.

Have you looked at `vcstool` and a couple of `.repos` files? Submodules can be rather confusing to newcomers, and setting up a ROS workspace with all dependencies takes 3 commands.

But it's not important.

**Comment by fmauch** [comment]
Is there anything to add from a driver's perspective? Otherwise I would go ahead and close this.

**Comment by xiaohuits** [comment]
I don't see a need to change the driver for now.

**Comment by ManueU** [comment]
Hi, 
I am testing this driver with two UR5. I followed the instructions written in the issue, but I have some questions because the system doesn't work. 
I did the following things: 
- set the correct IP addresses
- change the "reverse_port" and the "script_sender_port" values for one of the two robots
- obtain two different calibration files
- create two different controllers.yaml files 

In the following, my launch file: 
```

<?xml version="1.0"?>
<launch>
<group ns="masterArm">
<include file="$(find ur_robot_driver)/launch/ur5_bringup.launch">
	<arg name="robot_ip" value="192.168.1.4"/>
	<arg name="tf_prefix" value="m_"/>
	<arg name="controllers" value="joint_state_controller"/>
	<arg name="stopped_controllers" value=""/>
	<arg name="controller_config_file" value="$(find ur_robot_driver)/config/ur5_controllers_master.yaml"/>
       <arg name="kinematics_config" value="$(find ur_description)/config/URcalib/master_calibration.yaml"/>
</include> 
</group>

<group ns="slaveArm">
<include file="$(find ur_robot_driver)/launch/ur5_bringup.launch">
	<arg name="robot_ip" value="192.168.1.2"/>
	<arg name="reverse_port" value="50003"/>
	<arg name="script_sender_port" value="50004"/>
	<arg name="tf_prefix" value="s_"/>
	<arg name="controllers" value="joint_state_controller my_cartesian_motion_controller"/>
	<arg name="stopped_controllers" value=""/>
	<arg name="controller_config_file" value="$(find ur_robot_driver)/config/ur5_controllers_slave.yaml"/>
       <arg name="kinematics_config" value="$(find ur_description)/config/URcalib/slave_calibration.yaml"/> 
</include>
</group> 
</launch>
```

The questions are: 

- **Do I have to change the joints names in both controllers.yaml and calibration.yaml files?** 
I can see the following errors changing the joints names in both files. **Why?** **In which way I can solve it?** 

![Screenshot from 2021-02-12 19-22-32](https://user-images.githubusercontent.com/74501957/107861546-c366ea80-6e46-11eb-89ca-5fa5efbc7c8e.png)


- There's another error (the red one). **Do you know the way to solve it?**

![Screenshot from 2021-02-12 19-22-28](https://user-images.githubusercontent.com/74501957/107861601-2eb0bc80-6e47-11eb-82e1-a497b4afbb13.png)


- **What is the reason of this errors? Could you help me to solve it?** 

![Screenshot from 2021-02-12 19-21-44](https://user-images.githubusercontent.com/74501957/107861634-6f103a80-6e47-11eb-8531-3f332545c45a.png)


Thank you so much!

**Comment by fmauch** [comment]
First of all, your `controllers.yaml` files seem to have errors. Without posting them it's hard to tell what is wrong.

Second, the `tf_prefix` argument is not passed to the description file. It would probably make sense to create your own description file where both robots are instantiated with the correct prefixes. See [this comment](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/81#issuecomment-578418515) how to configure the joint names and controllers.

**Comment by gavanderhoorn** [comment]
@fmauch: there is the [`subst_value` attribute on `rosparam` elements](http://wiki.ros.org/roslaunch/XML/rosparam#Examples) which we *could* use to prefix names of joints in the `.yaml` files automatically with the value assigned to `tf_prefix`.

And the `prefix` arg of the `xacro:macro` could also be set from the `.launch` file.

That may make setting up multi-robot configurations a little easier.

(I'm not too sure about the `xacro:macro` part, it tends to confuse if you use `arg`s there too much)

**Comment by ManueU** [comment]
Thank you so much for your quick responses! 

> Without posting them it's hard to tell what is wrong.

In the following, my controllers.yaml file: 
```
# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: &loop_hz 125
  

# Settings for ros_control hardware interface
ur_hardware_interface:
   joints: &robot_joints
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: *loop_hz

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: *loop_hz

# Publish speed_scaling factor
speed_scaling_state_controller:
   type:         ur_controllers/SpeedScalingStateController
   publish_rate: *loop_hz

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
scaled_pos_joint_traj_controller:
   type: position_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      elbow_joint: {trajectory: 0.2, goal: 0.1}
      wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

pos_joint_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      elbow_joint: {trajectory: 0.2, goal: 0.1}
      wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

scaled_vel_joint_traj_controller:
   type: velocity_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   gains:
      #!!These values have not been optimized!!
      shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      shoulder_pan_joint: 1.0
      shoulder_lift_joint: 1.0
      elbow_joint: 1.0
      wrist_1_joint: 1.0
      wrist_2_joint: 1.0
      wrist_3_joint: 1.0
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

vel_joint_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   gains:
      #!!These values have not been optimized!!
      shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      shoulder_pan_joint: 1.0
      shoulder_lift_joint: 1.0
      elbow_joint: 1.0
      wrist_1_joint: 1.0
      wrist_2_joint: 1.0
      wrist_3_joint: 1.0
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

# Pass an array of joint velocities directly to the joints
joint_group_vel_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints: *robot_joints

robot_status_controller:
   type: industrial_robot_status_controller/IndustrialRobotStatusController
   handle_name: industrial_robot_status_handle
   publish_rate: 10


# Cartesian motion controller   
my_cartesian_motion_controller:
    type: "position_controllers/CartesianMotionController"
    end_effector_link: "tool0"
    robot_base_link: "base"
    target_frame_topic: "target_frame"
    joints: *robot_joints

    pd_gains:
        trans_x: {p: 15.0, d: 3.0}
        trans_y: {p: 15.0, d: 3.0}
        trans_z: {p: 15.0, d: 3.0}
        rot_x: {p: 15.0, d: 3.0} 
        rot_y: {p: 15.0, d: 3.0}
        rot_z: {p: 15.0, d: 3.0}

```

> See this comment how to configure the joint names and controllers.

 I don't understand the procedure to set the joint names and controllers from the cited comment. Could you explain it to me in others terms? 

@gavanderhoorn  Is this can be seen as an alternative to the comment cited by @fmauch?

Thank you!
